name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: "Update this repo's README.md with latest blog posts"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Pull in posts"
        uses: gautamkrishnar/blog-post-workflow@1.8.8
        with:
          feed_list: "https://metalhearf.fr/index.xml"
          max_post_count: "5"
          commit_message: "Update blog posts"
          comment_tag_name: "BLOG-POST-LIST"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          
